const GoogleStrategy = require('passport-google-oauth20').Strategy;
const User = require('../models/User');
const { v4: uuidv4 } = require('uuid'); // Required for the secret OBS key

module.exports = function(passport) {
    passport.use(new GoogleStrategy({
        clientID: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
        callbackURL: "/api/auth/google/callback"
    },
    async (accessToken, refreshToken, profile, done) => {
        // Prepare data for a potential new user
        const newUser = {
            googleId: profile.id,
            username: profile.displayName,
            email: profile.emails[0].value,
            isEmailVerified: true,
            // Create a default streamerId (slug) using their name + random numbers
            streamerId: profile.displayName.toLowerCase().replace(/\s+/g, '-') + '-' + Math.floor(1000 + Math.random() * 9000),
            // Secret OBS key is generated by the User model's default uuidv4()
        };

        try {
            // Check if user already exists by email
            let user = await User.findOne({ email: profile.emails[0].value });

            if (user) {
                // If they exist but don't have a googleId linked, link it now
                if (!user.googleId) {
                    user.googleId = profile.id;
                    await user.save();
                }
                return done(null, user);
            } else {
                // New user: Create them in Drope
                user = await User.create(newUser);
                return done(null, user);
            }
        } catch (err) {
            console.error("Google Auth Error:", err);
            return done(err, null);
        }
    }));

    // These allow passport to maintain user sessions
    passport.serializeUser((user, done) => done(null, user.id));
    passport.deserializeUser(async (id, done) => {
        try {
            const user = await User.findById(id);
            done(null, user);
        } catch (err) {
            done(err, null);
        }
    });
};